server:
  port: 8080
spring:
  r2dbc:
    url: ${MYSQL:r2dbc:mysql://localhost:3306/mydatabase}
    username: myuser
    password: secret

  sql:
    init:
      mode: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html